### PR TITLE
added NYU icons for tabs

### PR DESCRIPTION
**Pull request by taratran**

### CODE REVIEW

**Comment by de846** [comment]
I think a good approach would be to define the URL for this once and use something like the following on every view's template (the html files), instead of using the URL everywhere (since the image can change). Additionally, we should included it as a static asset this way so we aren't dependent on the resource being available.
`href="{% static 'favicon.ico' %}"`

**Comment by taratran** [comment]
Hi David, I appreciate the review + agree completely with what you said. Let's touch base during the stand-up w/ the rest of the team re: what image to use and I can proceed with changing my commit accordingly. Thanks!

**Comment by de846** [comment]
I don't have any problem with the image you selected. I think you just need to save an asset under the `mercury/static/mercury/` directory, then use the `{% static '<whatever_you_called> %}' tag. Want to give it a try?

**Comment by taratran** [comment]
On it now!

**Pull request merged**
